### ISSUE TITLE
git list just returns a bunch of json

### ISSUE THREAD

**Issue by Gozala** [Gozala/github#1]
Reported by [Jan](https://github.com/jberkel)

> I tried your bespin/gist plugin out but it doesn't work - a git list just returns a bunch of json.
> any ideas?

**Comment by Gozala** [comment]
I'm glad you've tried it and sorry that it didn't work out of the box for you. In order to investigate into issue you're getting I will need some more information, so can you please answer the questions below:
1. What version of bespin are you running ?
2. Where did you got the plugin or how did you installed it ? 
3. Which browser do you use and what version ?
4. Did you've set a settings (case sensitive):
   - github-user 
   - github-token
5. please paste a command your running
6. please paste a json output you see or a link to a screenshot with it (selecting output can be challenging but, possible with webinspector / firebug)

Thanks!

**Comment by jberkel** [comment]
1. bespin.mozilla.com
2. installed via plugin install (plugin install http://github.com/downloads/Gozala/github/gist-v0.1.1.zip)
3. chrome 8.0.552.11 dev
4. tried with and without token, same result
5. / 6 http://skitch.com/jberkel/d7bb1/bespin

**Comment by Gozala** [comment]
bespin is no longer maintained so is this addon! Closing.
